### ISSUE TITLE
Reverse Lookup of D3D11 texture fails

### ISSUE THREAD

**Issue by jamesu** [rextimmy/Torque3D#16]
Working on updating the oculus rift code to one of these branches.

I have a little problem in that when I use GFXD3D11TextureTarget with textures generated by the oculus sdk, the texture format is being erroneously reported as GFXFormatDXT3. It seems that the reverse lookup table for textures is not able to resolve the correct format for DXGI_FORMAT_R8G8B8A8_TYPELESS which would be something like GFXFormatR8G8B8A8.

This causes problems since I cant use these textures properly in render targets. I can work around it by explicitly looking for the type but it might be prudent to use a better lookup table.

**Comment by rextimmy** [comment]
Yeah just any more needed formats here https://github.com/rextimmy/Torque3D/blob/dx11_deferred/Engine/source/gfx/D3D11/gfxD3D11EnumTranslate.cpp#L43 . Let me know what you add and i'll chuck in

**Comment by jamesu** [comment]
From what I understand though you can have normal variants of that AND *_TYPELESS variants  of essentially the same format (at least in torque-land) which introduces ambiguity. I guess I could add in GFXFormatR8G8B8A8_TYPELESS etc though.

Also while I opted not to use an SRGB format, it's also a valid option with the SDK to use an SRGB variant (DXGI_FORMAT_R8G8B8A8_UNORM_SRGB) - though then again i'm not sure what plans if any are in place to support non-linear rendering in stock T3D (I know doing it in D3D9 is a PITA).

**Comment by rextimmy** [comment]
Yeah DX9 is what stopped me implementing sRGB for now in GL/DX11. Yep i agree GFXFormatR8G8B8A8_TYPELESS or something like that is a nice way of doing it. Talking of sRGB this current deferred branch does by default convert to a linear format, it can be disabled though. https://github.com/rextimmy/Torque3D/blob/dx11_deferred/Templates/Full/game/shaders/common/torque.hlsl#L289-L312  just watch out for that, this was all done before dx11 was in place as part of the deferred change over.

**Comment by rextimmy** [comment]
I should also point out i will be moving everything in dx11_deferred branch over to dx11_clean and sending a PR to the official repo very soon. Straight after that i will create a dx11_phase2 branch which will be performance fixes and the like, will be adding some new texture formats too, that might be a good time to add in anything you need for your oculus work
