### ISSUE TITLE
swap chain failed - debug mode

### ISSUE THREAD

**Issue by Azaezel** [rextimmy/Torque3D#9]
build procedure: cmake + manually adding the dx11 directory.
release- operates.
debug-  triggers https://github.com/rextimmy/Torque3D/blob/d3d11/Engine/source/gfx/D3D11/gfxD3D11Device.cpp#L311

**Comment by rextimmy** [comment]
Sorry az i didn't even notice this.

Oh you need D3D11*SDKLayers.dll installed, if your on win 10 you can can run the following command (need to be admin)

Dism /online /add-capability /capabilityname:Tools.Graphics.DirectX~~~~0.0.1.0

If your on earlier windows you need the SDK for Win 8.

I have an update for the cbuffers in D3D11 that i'm still finishing off, i would definitely wait till i get that uploaded before playing around

**Comment by rextimmy** [comment]
Oh yeah i haven't touched cmake but i did update projectgen to support d3d11. If you don't use the gui you can includeModule( 'd3d11' ) . I also added VS 2013 to the projectgen, very annoying converting that VS 2012 project file each time. I'll document this all in the thread over at torque3d.org when i create it pretty soon.

**Comment by Azaezel** [comment]
thanks. see pr to save you some hunting time.
